[workspace]
members = [
    # Provide simics 
    # Provide real simics APIs
    "simics-api-sys",
    "simics-api",
    "simics-api-macro",
    "simics",
    "simics-cli",
    "simics-tests",
    "simics-link",
    "simics-fuzz",
    # Modules
    "modules/confuse_module",
    # Targets
    "targets/hello-world",
    "targets/x509-parse",
    # Utilities
    "util/ipc-shm",
    "util/raw-cstr",
    "util/version-tools",
    "util/raffl-macro",
    "util/artifact-dependency",
]

[workspace.dependencies]
artifact-dependency = { path = "./util/artifact-dependency" }
simics-link = { path = "./simics-link" }
simics = { path = "./simics" }
confuse_module = { path = "./modules/confuse_module" }
simics-api-sys = { path = "./simics-api-sys" }
simics-api = { path = "./simics-api" }
simics-api-macro = { path = "./simics-api-macro" }
raw-cstr = { path = "./util/raw-cstr" }
version-tools = { path = "./util/version-tools" }
raffl-macro = { path = "./util/raffl-macro" }
ipc-channel = { git = "https://github.com/novafacing/ipc-channel.git", version = "0.16.0", features = [
    "memfd",
] }
libafl = { git = "https://github.com/AFLplusplus/LibAFL", branch = "libfuzzer" }

[profile.dev]
rpath = true

[profile.release]
rpath = true
