[workspace]
members = [
    # Provide simics 
    "confuse-simics-project",
    "confuse-simics-api",
    # Just provides common simics manifest tools for parsing/managing simics
    "confuse-simics-manifest",
    # Provides module signing utilities for creating simics modules
    "confuse-simics-module",
    # Fuzzer
    "confuse-fuzz",
    # Modules
    "modules/minimal-simics-module",
    "modules/ipc-test-module",
    "modules/confuse-module",
    # Targets
    "targets/hello-world",
    "targets/x509-parse",
    # Utilities
    "util/ipc-shm",
]

[workspace.dependencies]
confuse-simics-api = { path = "./confuse-simics-api" }
confuse-simics-project = { path = "./confuse-simics-project" }
confuse-simics-manifest = { path = "./confuse-simics-manifest" }
confuse-simics-module = { path = "./confuse-simics-module" }
confuse-fuzz = { path = "./confuse-fuzz" }
confuse-module = { path = "./modules/confuse-module" }
ipc-shm = { path = "./util/ipc-shm" }
ipc-channel = { git = "https://github.com/novafacing/ipc-channel.git", version = "0.16.0", features = [
    "memfd",
] }
