[package]
name = "confuse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libafl = "0.9.0"

[build-dependencies]
anyhow = "1.0.69"
const_format = "0.2.30"
flate2 = "1.0.25"
reqwest = { version = "0.11.14", features = ["blocking"] }
tar = "0.4.38"
