[workspace]
members = [
    # Provide simics 
    "confuse-simics-project",
    "confuse-simics-api",
    # Just provides common simics manifest tools for parsing/managing simics
    "confuse-simics-manifest",
    # Provides module signing utilities for creating simics modules
    "confuse-simics-modsign",
    # Fuzzer
    "confuse-fuzz",
    # Modules
    "modules/confuse-branch-tracer",
    "modules/minimal-simics-module",
    "modules/ipc-test-module",
    # Targets
    "targets/hello-world",
    # Utilities
    "util/ipc-shm",
]

[workspace.dependencies]
confuse-simics-api = { path = "./confuse-simics-api" }
confuse-simics-project = { path = "./confuse-simics-project" }
confuse-simics-manifest = { path = "./confuse-simics-manifest" }
confuse-simics-modsign = { path = "./confuse-simics-modsign" }
confuse-fuzz = { path = "./confuse-fuzz" }
