[workspace]
members = [
    # Provide simics and its modules
    "confuse-simics",
    # Provide the host interface to control simics and allow simics to talk
    "confuse-host-interface",
    # Fuzzer
    "confuse-fuzz",
    # HelloFuzz.efi edk2 UEFI module example
    "examples/hello-fuzzing",
]

[workspace.dependencies]
confuse-simics = { path = "./confuse-simics" }
