[workspace]
members = [
    # Provide simics and its APIs
    "confuse-simics",
    # Just provides common simics manifest tools for parsing/managing simics
    "confuse-simics-manifest",
    # Fuzzer
    "confuse-fuzz",
    # HelloFuzz.efi edk2 UEFI module example
    "examples/hello-fuzzing",

    # Modules
    "modules/confuse-branch-tracer",
    "modules/minimal/minimal-simics-module",
]

[workspace.dependencies]
confuse-simics = { path = "./confuse-simics" }
confuse-simics-manifest = { path = "./confuse-simics-manifest" }
