[workspace]
members = [
    # Provide simics and its modules
    "confuse-simics",
    # Just provides common simics manifest tools for parsing/managing simics
    "confuse-simics-manifest",
    # Fuzzer
    "confuse-fuzz",
    # HelloFuzz.efi edk2 UEFI module example
    "examples/hello-fuzzing",
]

[workspace.dependencies]
confuse-simics = { path = "./confuse-simics" }
confuse-simics-manifest = { path = "./confuse-simics-manifest" }
