[workspace]
members = [
    # Provide simics 
    # Provide real simics APIs
    "simics-api-sys",
    "simics-api",
    "simics-api-macro",
    "simics",
    "simics-cli",
    "simics-tests",
    "simics-link",
    "simics-fuzz",
    # Modules
    "confuse_module",
    # Targets
    "targets/hello-world",
    "targets/x509-parse",
    # Utilities
    "util/raw-cstr",
    "util/version-tools",
    "util/ffi-macro",
    "util/artifact-dependency",
]
default-members = [
    # Provide simics 
    # Provide real simics APIs
    "simics-api-sys",
    "simics-api",
    "simics-api-macro",
    "simics",
    "simics-cli",
    "simics-tests",
    "simics-link",
    "simics-fuzz",
    # Modules
    "confuse_module",
    # Utilities
    "util/raw-cstr",
    "util/version-tools",
    "util/ffi-macro",
    "util/artifact-dependency",
]

[workspace.dependencies]
artifact-dependency = { path = "./util/artifact-dependency" }
simics-link = { path = "./simics-link" }
simics = { path = "./simics" }
confuse_module = { path = "./confuse_module" }
simics-api-sys = { path = "./simics-api-sys" }
simics-api = { path = "./simics-api" }
simics-api-macro = { path = "./simics-api-macro" }
raw-cstr = { path = "./util/raw-cstr" }
version-tools = { path = "./util/version-tools" }
ffi-macro = { path = "./util/ffi-macro" }
libafl = { git = "https://github.com/AFLplusplus/LibAFL", branch = "libfuzzer" }
anyhow = "1.0.71"
# Match these versions to cargo_metadata -- it breaks on current versions
serde = "1.0.136"
serde_json = "1.0.79"

[profile.dev]
rpath = true

[profile.release]
rpath = true
