%YAML 1.2
---
description: QSP with UEFI App (Fuzzing)
params:
  apic_freq_mhz:
    type: int
    default: 133
  cpi:
    type: int
    default: 1
  cpu_comp_class:
    type: str
    default: "x86QSP1"
  freq_mhz:
    type: int
    default: 2000
  num_cores:
    type: int
    default: 1
  num_cores_small:
    type: int
    default: 0
  num_cpus:
    type: int
    default: 1
  num_threads:
    type: int
    default: 1
  num_threads_small:
    type: int
    default: 0
  hide_consoles:
    type: bool
    default: FALSE
  serial_console_bg_color:
    type: str
    default: "black"
  serial_console_fg_color:
    type: str
    default: "white"
  show_con0:
    type: bool
    default: TRUE
  show_con1:
    type: bool
    default: FALSE
  show_gfx_con:
    type: bool
    default: TRUE
  create_cdrom:
    type: str
    default: "sata"
  create_disk0:
    type: str
    default: "sata"
  disk0_image:
    type: file
    default: "%simics%/targets/x509-parse/minimal_boot_disk.craff"
  disk0_size:
    type: int
    default: 209715200
  tsc_factor:
    type: int
    default: 20
  connect_real_network:
    type: str
    default: "napt"
  create_network:
    type: bool
    default: TRUE
  create_service_node:
    type: bool
    default: TRUE
  dhcp_domain_name:
    type: str
    default: "network.sim"
  dhcp_pool_size:
    type: int
    default: 100
  eth_connector_vlan_id:
    type: int
    default: -1
  eth_vlan_enable:
    type: bool
    default: FALSE
  ip_address:
    type: str
    default: "auto"
  mac_address:
    type: str
    default: "auto"
  service_node_ip_address:
    type: str
    default: "10.10.0.1"
  service_node_setup:
    type: bool
    default: TRUE
  service_node_vlan_id:
    type: int
    default: -1
  create_osa:
    type: bool
    default: TRUE
  create_tracker:
    type: bool
    default: FALSE
  enable_break_on_reboot:
    type: bool
    default: FALSE
  enable_system_clock:
    type: bool
    default: FALSE
  real_time_mode:
    type: bool
    default: FALSE
  system_clock_class:
    type: str
    default: "clock"
  system_info:
    type: str
    default: "QSP x86 with externally provided Kernel/RootFs/InitRd"
  auto_start_uefi_shell:
    type: bool
    default: TRUE
  bios_image:
    type: file
    default: "%simics%/targets/qsp-x86/images/SIMICSX58IA32X64_1_1_0_r.fd"
  create_usb_tablet:
    type: bool
    default: FALSE
  machine_name:
    type: str
    default: "board"
  memory_megs:
    type: int
    default: 8192
  rtc_time:
    type: str
    default: "2021-06-10 10:41:54"
  startup_nsh:
    type: file
    default: "%simics%/targets/x509-parse/run_uefi_app.nsh"
  uefi_app:
    type: file
    default: "%simics%/targets/x509-parse/X509Parse.efi"
  eth_link:
    type: str
    output: true
  service_node:
    type: str
    output: true
  system:
    type: str
    output: true

script: "%simics%/scripts/app.py"
...