[package]
name = "x509-parse"
version = "0.1.0"
edition = "2021"

[dependencies]
confuse-simics-module = { workspace = true }
confuse-module = { workspace = true }
confuse-simics-project = { workspace = true }
confuse-fuzz = { workspace = true }
anyhow = "1.0.69"
env_logger = "0.10.0"
log = "0.4.17"
confuse-simics-manifest = { workspace = true }
indoc = "2.0.1"
ipc-channel = { workspace = true }
libafl = { workspace = true }
tempfile = "3.4.0"
chrono = "0.4.24"

[dev-dependencies]

[build-dependencies]
anyhow = "1.0.69"
confuse-simics-project = { workspace = true }
dockerfile-rs = "0.3.0"
