[package]
name = "artifact-dependency"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow.workspace = true
cargo_metadata = "0.15.4"
derive_builder = "0.12.0"
serde = { workspace = true, features = ["derive"] }
tracing = "0.1.37"
