[package]
name = "artifact-dependency"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
cargo_metadata = "0.15.4"
derive_builder = "0.12.0"
