[package]
name = "artifact-dependency"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
anyhow = "1.0.71"
cargo_metadata = "0.15.4"
derive_builder = "0.12.0"
serde = { version = "1.0.164", features = ["derive"] }
