[package]
name = "ipc-shm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
ipc-channel = { workspace = true }
memfd = "0.6.2"
memmap2 = "0.5.10"
serde = { version = "1.0.152", features = ["derive"] }
