[package]
name = "minimal-simics-module"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
confuse-simics = { workspace = true }

[build-dependencies]
anyhow = "1.0.69"
dotenvy_macro = "0.15.1"
confuse-simics-manifest = { workspace = true }
