[package]
name = "simics-api-sys"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
"6.0.163" = []
"6.0.164" = []
"6.0.165" = []
"6.0.166" = []
"6.0.167" = []
