
[package]
name = "simics-api-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
bytes = "1.4.0"
dockerfile-rs = "0.3.0"
reqwest = { version = "0.11.16", features = ["blocking"] }
tempfile = "3.5.0"
