name: Confuse Rust continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    container: amr-fm-registry.caas.intel.com/cache/library/ubuntu@sha256:83f0c2a8d6f266d687d55b5cb1cb2201148eb7ac449e4202d9646b9083f1cee0
    runs-on: [self-hosted, gasp]
    steps:
      - name: Install Dependencies
        run: |
          apt-get -y update && \
          apt-get -y install \
            git \
            curl \
            build-essential
      - name: Install SIMICS
        run: |
          mkdir -p "${HOME}/simics"
          cd "{HOME}/simics"
          curl -o simics-6-packages-2023-19-linux64.ispm https://registrationcenter-download.intel.com/akdlm/IRC_NAS/0554dff0-ac52-4d41-ae95-0befba095555/simics-6-packages-2023-19-linux64.ispm
          curl -o intel-simics-package-manager-1.7.2-linux64.tar.gz https://registrationcenter-download.intel.com/akdlm/IRC_NAS/0554dff0-ac52-4d41-ae95-0befba095555/intel-simics-package-manager-1.7.2-linux64.tar.gz
          tar -xvf intel-simics-package-manager-1.7.2-linux64.tar.gz
          ./intel-simics-package-manager-1.7.2/ispm packages --install-dir "${HOME}/simics" --install-bundle "${HOME}/simics/simics-6-packages-2023-19-linux64.ispm" --non-interactive
      - uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: ./.github/actions/toolchain
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy, cargo
          default: true
      - name: Set up .env
        run: |
          echo "SIMICS_HOME=${{ env.SIMICS_HOME }}" > .env
      - name: Build Project
        uses: ./.github/actions/cargo
        with:
          command: build
          args: --features=6.0.166
