name: Confuse Rust continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  REPO: "/__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}/"
  # Simics base
  SIMICS_PACKAGE_VERSION_1000: 6.0.166
  # QSP X86
  SIMICS_PACKAGE_VERSION_2096: 6.0.68
  # QSP CPU
  SIMICS_PACKAGE_VERSION_8112: 6.0.17

jobs:
  build:
    container: amr-fm-registry.caas.intel.com/cache/library/ubuntu@sha256:83f0c2a8d6f266d687d55b5cb1cb2201148eb7ac449e4202d9646b9083f1cee0
    runs-on: [self-hosted, gasp]
    steps:
      - name: Install Dependencies
        run: |
          apt-get -y update && \
          apt-get -y install \
            git \
            curl \
            build-essential
      - name: Install SIMICS (Internal)
        run: |
          mkdir -p "${HOME}/simics"
          cd "${HOME}/simics"
          curl -o intel-simics-package-manager-1.7.3-linux64.tar.gz https://af02p-or.devtools.intel.com/artifactory/simics-local/pub/simics-installer/external/1.7.3/intel-simics-package-manager-1.7.3-linux64.tar.gz
          tar -xvf intel-simics-package-manager-1.7.3-linux64.tar.gz
          echo "1000 ${{ secrets.SIMICS_PUBLIC_PACKAGE_KEY_1000 }}" >> SIMICS-PUBLIC-PACKAGE-DECRYPTION-KEY-FILE
          echo "2096 ${{ secrets.SIMICS_PUBLIC_PACKAGE_KEY_2096 }}" >> SIMICS-PUBLIC-PACKAGE-DECRYPTION-KEY-FILE
          echo "8112 ${{ secrets.SIMICS_PUBLIC_PACKAGE_KEY_8112 }}" >> SIMICS-PUBLIC-PACKAGE-DECRYPTION-KEY-FILE
          ./intel-simics-package-manager-1.7.3/ispm settings --config-file ispm.conf decryption-key-files --add SIMICS-PUBLIC-PACKAGE-DECRYPTION-KEY-FILE
          ./intel-simics-package-manager-1.7.3/ispm \
            --config-file ispm.conf \
            --non-interactive --verbose \
            --package-repo https://af02p-or.devtools.intel.com/ui/native/simics-repos/pub/simics-6/linux64/ \
            --install-dir "${HOME}/simics" \
            install 1000-${{ env.SIMICS_PACKAGE_VERSION_1000 }} 2096-${{ env.SIMICS_PACKAGE_VERSION_2096 }} 8112-${{ env.SIMICS_PACKAGE_VERSION_8112 }}
      - uses: actions/checkout@v3
      - name: Install Rust Toolchain (Requires Checkout)
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly --component rustfmt --component clippy --component miri --no-modify-path
      - name: Set up .env
        run: |
          echo "SIMICS_HOME=${HOME}/simics" > .env
      - name: Build Project
        run: |
          "${HOME}/.cargo/bin/cargo" build --features=${{ env.SIMICS_PACKAGE_VERSION_1000 }}
      - name: Check Project 
        run: |
          "${HOME}/.cargo/bin/cargo" clippy --features=${{ env.SIMICS_PACKAGE_VERSION_1000 }}
      - name: MIRI UB Checks
        run: |
          RUST_BACKTRACE=full MIRIFLAGS="-Zmiri-disable-isolation" "${HOME}/.cargo/bin/cargo" miri test
      - name: Test Project 
        run: |
          "${HOME}/.cargo/bin/cargo" test --features=${{ env.SIMICS_PACKAGE_VERSION_1000 }}
      - name: Build Docs
        run:
          cargo doc --features=${{ env.SIMICS_BASE_VERSION }}
      - name: Test Docs
        run: |
          "${HOME}/.cargo/bin/cargo" test --doc --features=${{ env.SIMICS_PACKAGE_VERSION_1000 }}
