name: Confuse Rust continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    container: amr-fm-registry.caas.intel.com/cache/library/ubuntu@sha256:83f0c2a8d6f266d687d55b5cb1cb2201148eb7ac449e4202d9646b9083f1cee0
    runs-on: [self-hosted, gasp]
    steps:
      - name: Install Dependencies
        run: |
          apt-get -y update && \
          apt-get -y install \
            git \
            curl \
            build-essential
      # - name: Install SIMICS (Public)
      #   run: |
      #     mkdir -p "${HOME}/simics"
      #     cd "${HOME}/simics"
      #     curl -o simics-6-packages-2023-19-linux64.ispm https://registrationcenter-download.intel.com/akdlm/IRC_NAS/0554dff0-ac52-4d41-ae95-0befba095555/simics-6-packages-2023-19-linux64.ispm
      #     curl -o intel-simics-package-manager-1.7.2-linux64.tar.gz https://registrationcenter-download.intel.com/akdlm/IRC_NAS/0554dff0-ac52-4d41-ae95-0befba095555/intel-simics-package-manager-1.7.2-linux64.tar.gz
      #     tar -xvf intel-simics-package-manager-1.7.2-linux64.tar.gz
      #     ./intel-simics-package-manager-1.7.2/ispm packages --install-dir "${HOME}/simics" --install-bundle "${HOME}/simics/simics-6-packages-2023-19-linux64.ispm" --non-interactive

      # TODO: Change to public for OSS
      - name: Install SIMICS (Internal)
        run: |
          mkdir -p "${HOME}/simics"
          cd "${HOME}/simics"
          curl -o intel-simics-package-manager-1.7.3-linux64.tar.gz https://af02p-or.devtools.intel.com/artifactory/simics-local/pub/simics-installer/external/1.7.3/intel-simics-package-manager-1.7.3-linux64.tar.gz
          tar -xvf intel-simics-package-manager-1.7.3-linux64.tar.gz
          ./intel-simics-package-manager-1.7.3/ispm \
            --non-interactive --verbose \
            --package-repo https://af02p-or.devtools.intel.com/ui/native/simics-local/pub/simics-6/linux64/ \
            --install-dir "${HOME}/simics" \
            install 1000-6.0.166 2096-6.0.68 8126-6.0.17
      - uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: ./.github/actions/toolchain
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy, cargo
          default: true
      - name: Set up .env
        run: |
          echo "SIMICS_HOME=${HOME}/simics" > .env
      - name: Build Project
        uses: ./.github/actions/cargo
        with:
          command: build
          args: --features=6.0.166
